[service]
name = "mm-gc"

[runtime]
kind = "rust"

[headless]
singleton = true

[databases]
db-mm-state = {}
redis-mm = {}

[resources.single-node]
cpu = 50
memory = 64

[resources.distributed]
cpu = 100
memory = 128

