[service]
name = "user-presence-gc"

[runtime]
kind = "rust"

[headless]
singleton = true

[databases]
redis-user-presence = {}

[resources.single-node]
cpu = 50
memory = 64

[resources.distributed]
cpu = 100
memory = 128

